{% set name = "red-molsim" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/red-molsim/red_molsim-{{ version }}.tar.gz
  sha256: b9a8b32b03963228f1a8b4cec5628919344368915683ac1e448b4975b2cb891b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python >=3.8
    - importlib-resources
    - numpy
    - scipy
    - matplotlib-base
    - statsmodels
    - numba

test:
  imports:
    - red
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fjclark/red
  summary: Robust Equilibration Detection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A Python package for detecting equilibration in time series where an initial transient is followed by a stationary distribution.
  doc_url: https://fjclark.github.io/red/latest/


extra:
  recipe-maintainers:
    - Roy-Haolin-Du
    - fjclark
